spring:
  jackson:
   searialization:
    write-dates-as-timestamps: false
  messages:
   basename: messages
  security:
   user:
    name: username
    password: password
  jpa:
   show-sql: true
  h2:
   console:
    enabled: true
  datasource:
   url: jdbc:h2:mem:testdb
   defer-datasource-initialization: true 
management:
  endpoints:
   web:
    exposure:
     include: "*"